#33- Automate DB creation for dev environment- Aisha Athman Lali
LauraSantiag0/Love-Me-Tender pull request #47
Opened 2024-07-27 08:26 UTC by aishaathmanlali

## Description

This is a PR for automating DB for dev environment. I have included the connection string to a shared DB

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

2024-07-27 08:40 UTC, soonick requested changes

2024-07-27 08:40 UTC, soonick commented on database/database.json
> +		"host": "dpg-cqhc5vdds78s73bd159g-a.virginia-postgres.render.com",
Never commit secrets

2024-07-27 11:16 UTC, beaumoaj reviewed
I would expect to see an SQL script here to set up the database containing 
- create table statements
- insert statements
- perhaps with a conditional drop database and create database at the start so anyone can just run it and set up a database.

Once the forms send data into the database then the insert statements are no longer necessary as you can create your own data from the UI but there still needs to be a script with the create table statements

2024-07-27 11:18 UTC, soonick commented
@beaumoaj , we have database migrations set up for our database. We just need to run the migrations every time the system is started, and the migrations take care of everything you mentioned.

2024-07-29 08:41 UTC, soonick requested changes

2024-07-29 08:41 UTC, soonick commented on database/migrations/sqls/20240723172844-attachments-table-and-modifications-to-tender-table-up.sql
> +ALTER TABLE tender
This doesn't belong in this PR

2024-07-29 08:41 UTC, soonick commented on database/database.json
> +		"port": "${DB_PORT}"
We need to do this for production. For the dev environment, we can leave it the way it was before

2024-07-29 08:41 UTC, soonick commented on scripts/create_dev_db.sh
> +#!/bin/bash
We don't need this script. This command already takes care of everything:

```
node ../node_modules/db-migrate/bin/db-migrate up
```

The only thing we need is to make sure this command is automatically called every time we start the dev version of the server

2024-07-29 14:52 UTC, soonick approved these changes

2024-07-29 14:52 UTC, merged